@ACCESS_TOKEN = 8mu9dgvlpxvagwc8kr97y7gdovfwebd
@STORE_HASH = b5cvpaoito

###

GET https://api.bigcommerce.com/stores/{{STORE_HASH}}/v3/catalog/products
X-Auth-Token: {{ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json